### ISSUE TITLE
Wrong decryption!!

### ISSUE THREAD

**Issue by mahyamaftouni** [kunerd/jpaillier#10]
Hi
In the encrypt function the do while condition should be 
`r.compareTo(n) >= 0 || !n.gcd(r).equals(BigInteger.ONE)`
instead of just:
`r.compareTo(n) >= 0`
cause in paillier r is coprime with n!

and check uniqueness of p and q in keybuilder! 
any way i used your codes, Thanks :+1:

**Comment by BARJ** [comment]
Hi @mahyamaftouni , could you please explain why it is necessary to add:

`r.compareTo(n) >= 0 || !n.gcd(r).equals(BigInteger.ONE)`

Do you have a source?

According to the wikipedia page, r only has to be a random number of the set Z^*_n

**Comment by kunerd** [comment]
@mahyamaftouni I think @BARJ is right, see page 7 on http://www.cs.tau.ac.il/%7Efiat/crypt07/papers/Pai99pai.pdf

> select a random r < n
